In [2]:
import numpy as np
n1 = np.array([23,14,76,81])
n1.dtype

dtype('int64')

In [4]:
# converting the arr into float from int :
n1 = np.array([23,14,76,81], dtype = "float64")
n1

array([23., 14., 76., 81.])

In [5]:
n1.astype("float") 

array([23., 14., 76., 81.])

In [6]:
# example of memory usage : 
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)

24
12


In [7]:
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j])
arr

array([1.+2.j, 3.+4.j, 5.+6.j])

In [8]:
arr.dtype

dtype('complex128')

In [9]:
# real world example of broadcasting, with the help of datasets : 
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [11]:
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])
np.mean(data)

np.float64(30.0)