In [2]:
# creating 3D array : 
import numpy as np
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,12,13]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 12, 13]]])

In [3]:
arr.shape

(2, 2, 3)

In [4]:
print(arr[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [5]:
print(arr[:, 1, 2])

[ 6 13]


In [6]:
print(arr[:, 1, :])

[[ 4  5  6]
 [10 12 13]]
