In [1]:
import numpy as np
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [2]:
# some methods of numpy array for creating an array from scratch :

In [5]:
# for getting an array full of 0's :
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# for getting an array full of any num let say 8 :
np.full((3,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [7]:
# for getting an array which is evenly spaced :
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
# for getting an identity matrix : 
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
# for getting an array in some range : 
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
# properities of numpy arrays : 

In [12]:
myarr = np.array([[1,2,3], [4,5,6], [6,7,8], [9, 10, 11]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
print("shape : ", myarr.shape)
print("size : ", myarr.size)
print("datatype : ", myarr.dtype)
print("dimensions : ", myarr.ndim) 

shape :  (4, 3)
size :  12
datatype :  int64
dimensions :  2


In [14]:
# flatten and reshaping the array : 

In [16]:
print(myarr.shape)

(4, 3)


In [18]:
reshaped = myarr.reshape(2,6) 
reshaped

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
flattened = myarr.flatten()
flattened

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [9]:
import numpy as np 
myarr = np.array([[1,2,3], [4,5,6], [6,7,8], [9, 10, 11]]) 
flat = myarr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [6]:
# indexing : 
print(flat[0])
print(flat[-5])

1
7


In [10]:
# slicing :
print(flat[:3], flat[::4], flat[1:5])

[1 2 3] [1 5 8] [2 3 4 5]


In [2]:
import numpy as np
nump_arr = np.array([10,20.30,40,50,60,70,80,100])
print(nump_arr.shape)

(8,)


In [13]:
import numpy as np
import time
size = 1_000
l1 = list(range(size))
l2 = list(range(size)) 
start = time.time()
mul = [x*y for x, y in zip(l1,l2)]
end = time.time()
print("time taken : ", end-start)
print(mul[1:10])

time taken :  0.0007336139678955078
[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [14]:
import numpy as np
import time
size = 1_000
n1 = np.array(list(range(size)))
n2 = np.array(list(range(size))) 
start = time.time()
mul_np = n1 * n2 
end = time.time()
print("time taken : ", end-start)
print(mul_np[1:10]) 

time taken :  0.0006113052368164062
[ 1  4  9 16 25 36 49 64 81]


In [16]:
import numpy as np
import time 
size = 1_000_0000
np_data = np.array(range(size))
print("size of np_data : ", np_data.nbytes, "bytes")

size of np_data :  80000000 bytes
