In [1]:
# list v/s numpy : in terms of speed

In [4]:
# using python list : 
import numpy as np 
import time
# creating list :
size = 1_000_000
l1 = list(range(size))
l2 = list(range(size))
start = time.time()
add = [x+y for x,y in zip(l1,l2)] 
end = time.time()
print(add[0:10])
print("time taken : ", end-start) 

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
time taken :  0.3012559413909912


In [3]:
# using numpy arrays :
import numpy as np 
import time 
size = 1_000_000
l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))
start = time.time()
add = l1 + l2
end = time.time()
print(add[0:10])
print("time taken : ", end-start) 

[ 0  2  4  6  8 10 12 14 16 18]
time taken :  0.05405712127685547


In [ ]:
# above programs are showing that numpy is way more faster than typical python list. 

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
# finding size of numpy arr and list : 
import sys
list_data = list(range(1000))
numpy_data = np.array(list(range(1000)))
print("python list size : ", sys.getsizeof(list_data), "bytes")
print("numpy array size : ", numpy_data.nbytes, "bytes") 

python list size :  8056 bytes
numpy array size :  8000 bytes


In [9]:
l = [x ** 2 for x in l1]
print("time taken : ", end-start)

time taken :  0.3012559413909912


In [11]:
numpy_squares = arr ** 2
print("time taken : ", end-start) 

time taken :  0.3012559413909912


In [15]:
# Python list (loop-based)
start = time.time()
list_squares = [x ** 2 for x in l1]
end = time.time()
print(end-start)
# NumPy (vectorized)
start = time.time()
numpy_squares = arr ** 2
end = time.time()
print(end-start)

0.3558471202850342
0.00029540061950683594
